apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kiwix-pvc
  namespace: kiwix
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: kiwix-nfs-csi
