---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fah-nfs-pvc
  namespace: foldingathome
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: fah-nfs-csi
  resources:
    requests:
      storage: 10Gi
